create table public.type (
  type_id bigint generated by default as identity not null,
  name text not null,
  title_bg_color text null,
  sub_bg_color text null,
  sub_text_color text null,
  constraint type_pkey primary key (type_id)
) TABLESPACE pg_default;

create table public.gallery (
  g_id bigint not null,
  title text null,
  thumb1 text null,
  thumb2 text null,
  date timestamp with time zone null,
  filecount integer null,
  type_id bigint null,
  view_count integer not null default 0,
  ver smallint not null default '0'::smallint,
  constraint gallery_pkey primary key (g_id),
  constraint gallery_type_id_fkey foreign KEY (type_id) references type (type_id) on update CASCADE on delete CASCADE
) TABLESPACE pg_default;

create table public.tag (
  tag_id bigint generated by default as identity not null,
  name text null,
  constraint tag_pkey primary key (tag_id),
  constraint tag_name_key unique (name)
) TABLESPACE pg_default;

create table public.gallery_tag (
  g_id bigint not null,
  tag_id bigint not null,
  constraint gallery_tag_pkey primary key (g_id, tag_id),
  constraint gallery_tag_g_id_fkey foreign KEY (g_id) references gallery (g_id) on update CASCADE on delete CASCADE,
  constraint gallery_tag_tag_id_fkey foreign KEY (tag_id) references tag (tag_id) on update CASCADE on delete CASCADE
) TABLESPACE pg_default;

create index IF not exists gallery_tag_tag_id_g_id_idx on public.gallery_tag using btree (tag_id, g_id) TABLESPACE pg_default;

create table public.notification (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  title text null,
  content text null,
  constraint notification_pkey primary key (id)
) TABLESPACE pg_default;

create table public.profiles (
  user_id uuid not null,
  tag_like_limit integer not null default 120,
  gallery_like_limit integer not null default 100,
  tag_dislike_limit integer not null default 150,
  constraint profiles_pkey primary key (user_id),
  constraint profiles_id_fkey foreign KEY (user_id) references auth.users (id) on update CASCADE on delete CASCADE
) TABLESPACE pg_default;

create table public.ranking (
  rank_type text not null,
  period text not null,
  ids bigint[] not null,
  updated_at timestamp with time zone null default now(),
  constraint ranking_pkey primary key (rank_type, period)
) TABLESPACE pg_default;

create table public.user_gallery_like (
  user_id uuid not null default auth.uid (),
  g_id bigint not null,
  created_at timestamp with time zone null default now(),
  constraint user_gallery_like_pkey primary key (user_id, g_id),
  constraint user_gallery_like_g_id_fkey foreign KEY (g_id) references gallery (g_id) on update CASCADE on delete CASCADE,
  constraint user_gallery_like_user_id_fkey foreign KEY (user_id) references auth.users (id) on update CASCADE on delete CASCADE
) TABLESPACE pg_default;

create table public.user_tag_dislike (
  user_id uuid not null,
  tag_id bigint not null,
  created_at timestamp with time zone not null default now(),
  constraint user_tag_dislike_pkey primary key (user_id, tag_id),
  constraint user_tag_dislike_tag_id_fkey foreign KEY (tag_id) references tag (tag_id) on update CASCADE on delete CASCADE,
  constraint user_tag_dislike_user_id_fkey foreign KEY (user_id) references auth.users (id) on update CASCADE on delete CASCADE
) TABLESPACE pg_default;

create table public.user_tag_like (
  user_id uuid not null default auth.uid (),
  tag_id bigint not null,
  created_at timestamp with time zone null default now(),
  constraint user_tag_like_pkey primary key (user_id, tag_id),
  constraint user_tag_like_tag_id_fkey foreign KEY (tag_id) references tag (tag_id) on update CASCADE on delete CASCADE,
  constraint user_tag_like_user_id_fkey foreign KEY (user_id) references auth.users (id) on update CASCADE on delete CASCADE
) TABLESPACE pg_default;